// src/config/topics.map.js

// This is the master keyword map.
// Structure:
// "Topic Name" → ["keyword1", "keyword2", "phrase that means this topic"]
//
// Rules we followed when building this map:
// 1. All keywords are lowercase — we lowercase the input text before matching
// 2. Longer phrases come first so "longest common subsequence" matches
//    before just "subsequence"
// 3. We include common abbreviations — "dp", "bfs", "dfs", "lru" etc.

const TOPICS_MAP = {
  "Dynamic Programming": [
    "dynamic programming",
    "dp",
    "memoization",
    "tabulation",
    "longest common subsequence",
    "lcs",
    "longest increasing subsequence",
    "lis",
    "knapsack",
    "coin change",
    "matrix chain",
    "edit distance",
    "fibonacci",
    "climbing stairs",
    "minimum path sum",
    "partition",
    "palindrome dp",
    "word break",
    "decode ways",
    "unique paths",
    "maximum subarray",
    "kadane",
  ],

  Arrays: [
    "array",
    "subarray",
    "prefix sum",
    "suffix sum",
    "two pointer",
    "two pointers",
    "kadane's algorithm",
    "stock buy sell",
    "rotate array",
    "spiral matrix",
    "next greater element",
    "product except self",
    "missing number",
    "duplicate number",
    "merge intervals",
    "interval",
    "rearrange",
    "move zeroes",
  ],

  Strings: [
    "string",
    "substring",
    "palindrome",
    "anagram",
    "pattern matching",
    "kmp",
    "rabin karp",
    "z algorithm",
    "longest palindromic",
    "string manipulation",
    "character frequency",
    "string compression",
    "valid parentheses",
    "roman numerals",
    "atoi",
  ],

  "Linked List": [
    "linked list",
    "singly linked",
    "doubly linked",
    "reverse linked list",
    "cycle detection",
    "floyd",
    "merge two sorted lists",
    "remove nth node",
    "intersection of linked list",
    "lru cache",
    "lru",
    "copy list with random pointer",
  ],

  Trees: [
    "tree",
    "binary tree",
    "bst",
    "binary search tree",
    "inorder",
    "preorder",
    "postorder",
    "level order",
    "height of tree",
    "diameter of tree",
    "lowest common ancestor",
    "lca",
    "path sum",
    "serialize deserialize",
    "balanced tree",
    "complete tree",
    "mirror tree",
    "symmetric tree",
    "flatten tree",
    "trie",
  ],

  Graphs: [
    "graph",
    "bfs",
    "dfs",
    "breadth first",
    "depth first",
    "shortest path",
    "dijkstra",
    "bellman ford",
    "topological sort",
    "cycle in graph",
    "connected components",
    "union find",
    "disjoint set",
    "minimum spanning tree",
    "kruskal",
    "prim",
    "flood fill",
    "number of islands",
    "bipartite",
    "strongly connected",
  ],

  "Sliding Window": [
    "sliding window",
    "window",
    "longest substring without repeating",
    "maximum sum subarray of size k",
    "minimum window substring",
    "substring with all characters",
    "find all anagrams",
  ],

  "Binary Search": [
    "binary search",
    "search in rotated",
    "find peak element",
    "median of two sorted",
    "search a 2d matrix",
    "first and last position",
    "kth smallest",
    "kth largest",
    "aggressive cows",
    "book allocation",
    "painter partition",
  ],

  "Stacks and Queues": [
    "stack",
    "queue",
    "monotonic stack",
    "next greater",
    "largest rectangle histogram",
    "trapping rain water",
    "min stack",
    "implement queue using stack",
    "sliding window maximum",
    "deque",
    "circular queue",
  ],

  Heaps: [
    "heap",
    "priority queue",
    "min heap",
    "max heap",
    "kth largest element",
    "top k frequent",
    "merge k sorted",
    "median from data stream",
    "task scheduler",
  ],

  "Recursion and Backtracking": [
    "recursion",
    "backtracking",
    "n queens",
    "sudoku solver",
    "permutations",
    "combinations",
    "subsets",
    "power set",
    "word search",
    "rat in a maze",
    "generate parentheses",
  ],

  Sorting: [
    "sorting",
    "merge sort",
    "quick sort",
    "heap sort",
    "counting sort",
    "radix sort",
    "sort colors",
    "sort linked list",
    "wiggle sort",
    "meeting rooms",
  ],

  Hashing: [
    "hash",
    "hashmap",
    "hashtable",
    "hash table",
    "frequency count",
    "two sum",
    "four sum",
    "group anagrams",
    "longest consecutive sequence",
    "subarray sum equals k",
  ],

  "Bit Manipulation": [
    "bit",
    "bitwise",
    "xor",
    "and operation",
    "or operation",
    "single number",
    "power of two",
    "counting bits",
    "reverse bits",
    "hamming distance",
    "bit manipulation",
  ],

  "System Design": [
    "system design",
    "design",
    "scalability",
    "load balancer",
    "database design",
    "caching",
    "microservices",
    "rate limiting",
    "consistent hashing",
    "cdn",
    "message queue",
    "pub sub",
    "design twitter",
    "design uber",
    "design whatsapp",
  ],

  "Operating Systems": [
    "operating system",
    "os",
    "process",
    "thread",
    "deadlock",
    "mutex",
    "semaphore",
    "scheduling",
    "memory management",
    "paging",
    "virtual memory",
    "context switch",
  ],

  Database: [
    "sql",
    "database",
    "query",
    "join",
    "index",
    "normalization",
    "transaction",
    "acid",
    "nosql",
    "mongodb",
    "postgresql",
    "mysql",
  ],

  "Object Oriented Design": [
    "oops",
    "object oriented",
    "class",
    "inheritance",
    "polymorphism",
    "encapsulation",
    "abstraction",
    "design pattern",
    "solid principles",
    "singleton",
    "factory pattern",
    "observer pattern",
  ],
};

module.exports = TOPICS_MAP;
